# Filepath: docker-compose.yml
services:
  db:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
    ports:
      - "3306:3306"
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
      - mysql-data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root"]
      interval: 10s
      timeout: 5s
      retries: 5

  auth-service:
    build: ./auth-service
    restart: always
    ports:
      - "8080:8080"
    environment:
      DB_SOURCE: "mysql://root:@tcp(db:3306)/auth-service?parseTime=true"
      JWT_SECRET_KEY: "pats_kats_kits_kuts_mahou_11231231313"
    depends_on:
      db:
        condition: service_healthy

  cart-service:
    build: ./cart-service
    restart: always
    ports:
      - "8081:8080"
    environment:
      DB_SOURCE: "root:@tcp(db:3306)/cart-service?parseTime=true"
      API_PORT: "8080"
      JWT_SECRET: "pats_kats_kits_kuts_mahou_11231231313"
    depends_on:
      db:
        condition: service_healthy

  product-service:
    build: ./product-service
    restart: always
    ports:
      - "8082:8080"
    environment:
      DB_SOURCE: "root:@tcp(db:3306)/product-service?parseTime=true"
      API_PORT: "8080"
      JWT_SECRET: "pats_kats_kits_kuts_mahou_11231231313"
    depends_on:
      db:
        condition: service_healthy

volumes:
  mysql-data: